export const SET_BILL = 'SET_BILL',
   SET_STATIC_PERCENT = 'SET_STATIC_PERCENT',
   SET_CUSTOM_PERCENT = 'SET_CUSTOM_PERCENT',
   SET_PEOPLE_COUNT = 'SET_PEOPLE_COUNT',
   SET_ACTIVE_ID = 'SET_ACTIVE_ID';